name: Base Repo RCE Proof

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  rce-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run a command
        run: |
          uname -a
